// SPDX-FileCopyrightText: 2026 Aditya Mehra <aix.m@outlook.com>
//
// SPDX-License-Identifier: LGPL-3.0-or-later

/**
 * @file GeneratedMediaScreen.kt
 * @brief Gallery screen for images and audio clips generated by the host
 *        during a conversation, with inline image decoding on tap and
 *        platform audio playback (one clip at a time, with a stop control)
 *        via MediaPlayer.
 * @layer UI
 * @dependencies Jetpack Compose, MainViewModel, MainUiState, GeneratedFileUi,
 *               android.media.MediaPlayer, android.graphics.BitmapFactory
 */

package com.verzeta.android.ui.chat

import android.util.Base64
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.aspectRatio
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.lazy.grid.GridCells
import androidx.compose.foundation.lazy.grid.LazyVerticalGrid
import androidx.compose.foundation.lazy.grid.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Audiotrack
import androidx.compose.material.icons.filled.Image
import androidx.compose.material.icons.filled.PlayArrow
import androidx.compose.material.icons.filled.SaveAlt
import androidx.compose.material.icons.filled.Stop
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.SegmentedButton
import androidx.compose.material3.SegmentedButtonDefaults
import androidx.compose.material3.SingleChoiceSegmentedButtonRow
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateMapOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import com.verzeta.android.DownloadKind
import com.verzeta.android.MainUiState
import com.verzeta.android.MainViewModel
import com.verzeta.android.data.chat.GeneratedFileUi
import com.verzeta.android.data.host.HostStatus
import com.verzeta.android.ui.components.EmptyState
import com.verzeta.android.ui.tools.TopBar
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import android.graphics.BitmapFactory

/**
 * Generated images + audio gallery. Android port of
 * `frontend/pages/ArtifactViewerPage.qml`. Two top-level segments:
 *   - **Images**: 2-column grid; tap a tile → fetch via `image.download`,
 *     decode the base64 → render in the tile. When the host truncated the
 *     download the tile is marked "Partial". A failed download or decode
 *     is reported in the app-wide snackbar.
 *   - **Audio**: list with a Play / Stop control. Playback uses the
 *     platform [android.media.MediaPlayer] (decoded base64 bytes → temp
 *     file → start). Only one clip plays at a time; starting another, or
 *     leaving the screen, stops and releases the current one.
 *
 * `image.generated` / `audio.generated` events update the lists live —
 * server-filtered by msg.subscribe so the gallery for conv A doesn't
 * mutate when conv B generates a file.
 */
@OptIn(ExperimentalComposeUiApi::class)
@Composable
fun GeneratedMediaScreen(state: MainUiState, actions: MainViewModel) {
    val convId = state.selectedConversationId ?: return
    val connected = state.activeHost?.status == HostStatus.Connected
    val images = state.convImages[convId].orEmpty()
    val audio = state.convAudio[convId].orEmpty()

    LaunchedEffect(convId, connected) {
        if (connected) actions.loadGeneratedMediaForConversation(convId)
    }

    var tab by remember { mutableStateOf(MediaTab.Images) }

    Column(modifier = Modifier.fillMaxSize()) {
        TopBar(
            title = "Generated media",
            subtitle = "${images.size} image${if (images.size == 1) "" else "s"} · ${audio.size} audio",
            onBack = actions::closeGeneratedMedia,
            onRefresh = if (connected) ({ actions.loadGeneratedMediaForConversation(convId) }) else null,
        )
        HorizontalDivider(color = MaterialTheme.colorScheme.outlineVariant)

        SingleChoiceSegmentedButtonRow(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 16.dp, vertical = 8.dp),
        ) {
            MediaTab.entries.forEachIndexed { index, mt ->
                SegmentedButton(
                    selected = tab == mt,
                    onClick = { tab = mt },
                    shape = SegmentedButtonDefaults.itemShape(index = index, count = MediaTab.entries.size),
                    label = { Text("${mt.title} (${if (mt == MediaTab.Images) images.size else audio.size})") },
                )
            }
        }

        when (tab) {
            MediaTab.Images -> ImagesGrid(images = images, convId = convId, actions = actions)
            MediaTab.Audio -> AudioList(audio = audio, convId = convId, actions = actions)
        }
    }
}

private enum class MediaTab(val title: String) { Images("Images"), Audio("Audio") }

@Composable
private fun ImagesGrid(images: List<GeneratedFileUi>, convId: String, actions: MainViewModel) {
    if (images.isEmpty()) {
        EmptyState(
            title = "No images yet",
            detail = "Images generated by tools or LLM responses will appear here.",
        )
        return
    }
    // Lazily decoded bitmaps cached by file name. We only fetch on tile
    // tap; before that the tile shows a placeholder icon.
    val decoded = remember { mutableStateMapOf<String, ImageBitmap>() }
    // File names whose download the host cut short (`truncated`).
    val partial = remember { mutableStateMapOf<String, Boolean>() }
    val scope = rememberCoroutineScope()
    LazyVerticalGrid(
        columns = GridCells.Fixed(2),
        modifier = Modifier.fillMaxSize().padding(horizontal = 12.dp),
    ) {
        items(images, key = { it.fileName }) { img ->
            ImageTile(
                img = img,
                bitmap = decoded[img.fileName],
                partial = partial[img.fileName] == true,
                onTap = {
                    if (decoded.containsKey(img.fileName)) return@ImageTile
                    scope.launch {
                        actions.downloadFile(DownloadKind.Image, convId, img.fileName)
                            .onSuccess { payload ->
                                val bmp = withContext(Dispatchers.IO) {
                                    runCatching {
                                        val bytes = Base64.decode(payload.contentBase64, Base64.NO_WRAP)
                                        BitmapFactory.decodeByteArray(bytes, 0, bytes.size)
                                            ?.asImageBitmap()
                                    }.getOrNull()
                                }
                                if (bmp != null) {
                                    decoded[img.fileName] = bmp
                                    if (payload.truncated) partial[img.fileName] = true
                                } else {
                                    actions.reportError("Could not display ${img.fileName}")
                                }
                            }
                            .onFailure { e ->
                                actions.reportError(
                                    "Could not download ${img.fileName}: ${e.message ?: "unknown error"}",
                                )
                            }
                    }
                },
            )
        }
    }
}

@Composable
private fun ImageTile(
    img: GeneratedFileUi,
    bitmap: ImageBitmap?,
    partial: Boolean,
    onTap: () -> Unit,
) {
    Box(
        modifier = Modifier
            .padding(4.dp)
            .fillMaxWidth()
            .aspectRatio(1f)
            .clip(RoundedCornerShape(8.dp))
            .background(MaterialTheme.colorScheme.surfaceContainerHigh)
            .clickable(onClick = onTap),
    ) {
        if (bitmap != null) {
            Image(
                bitmap = bitmap,
                contentDescription = img.fileName,
                contentScale = ContentScale.Crop,
                modifier = Modifier.fillMaxSize(),
            )
            if (partial) {
                Text(
                    "Partial",
                    style = MaterialTheme.typography.labelSmall,
                    color = MaterialTheme.colorScheme.onErrorContainer,
                    modifier = Modifier
                        .align(Alignment.TopStart)
                        .padding(6.dp)
                        .clip(RoundedCornerShape(4.dp))
                        .background(MaterialTheme.colorScheme.errorContainer)
                        .padding(horizontal = 6.dp, vertical = 2.dp),
                )
            }
        } else {
            Column(
                modifier = Modifier.fillMaxSize().padding(8.dp),
                horizontalAlignment = Alignment.CenterHorizontally,
                verticalArrangement = Arrangement.Center,
            ) {
                Icon(
                    Icons.Filled.Image,
                    contentDescription = null,
                    tint = MaterialTheme.colorScheme.onSurfaceVariant,
                    modifier = Modifier.size(36.dp),
                )
                Spacer(Modifier.size(6.dp))
                Text(
                    img.fileName,
                    style = MaterialTheme.typography.labelSmall.copy(fontFamily = FontFamily.Monospace),
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    maxLines = 2,
                    overflow = TextOverflow.Ellipsis,
                )
            }
        }
    }
}

@Composable
private fun AudioList(audio: List<GeneratedFileUi>, convId: String, actions: MainViewModel) {
    if (audio.isEmpty()) {
        EmptyState(
            title = "No audio yet",
            detail = "TTS clips and audio tool outputs will appear here.",
        )
        return
    }
    val context = LocalContext.current
    val scope = rememberCoroutineScope()
    val playback = remember { ClipPlayback() }
    DisposableEffect(Unit) {
        onDispose { playback.stop() }
    }
    LazyColumn(modifier = Modifier.fillMaxSize().padding(horizontal = 16.dp)) {
        items(audio, key = { it.fileName }) { clip ->
            Spacer(Modifier.height(8.dp))
            AudioRow(
                clip = clip,
                playing = playback.playingFile == clip.fileName,
                onStop = { playback.stop() },
                onPlay = {
                    // One clip at a time: stop whatever is playing first.
                    playback.stop()
                    scope.launch {
                        actions.downloadFile(DownloadKind.Audio, convId, clip.fileName)
                            .onSuccess { payload ->
                                val started = withContext(Dispatchers.IO) {
                                    playback.prepare(
                                        bytes = Base64.decode(payload.contentBase64, Base64.NO_WRAP),
                                        extension = clip.fileName.substringAfterLast('.', "bin"),
                                        cacheDir = context.cacheDir,
                                    )
                                }
                                if (started) {
                                    playback.start(clip.fileName)
                                } else {
                                    actions.reportError("Could not play ${clip.fileName}")
                                }
                            }
                            .onFailure { e ->
                                actions.reportError(
                                    "Could not download ${clip.fileName}: ${e.message ?: "unknown error"}",
                                )
                            }
                    }
                },
            )
        }
        item { Spacer(Modifier.height(40.dp)) }
    }
}

/**
 * Holds the single audio clip that is playing, so a new tap or leaving the
 * screen stops and releases it, and the temp file is always deleted.
 */
private class ClipPlayback {
    private var player: android.media.MediaPlayer? = null
    private var prepared: android.media.MediaPlayer? = null
    private var tempFile: java.io.File? = null

    /** File name of the clip that is playing, or null. Observed by the rows. */
    var playingFile by mutableStateOf<String?>(null)
        private set

    /**
     * Write [bytes] to a temp file and prepare a player for it. Runs off
     * the main thread.
     *
     * @returns true when the player is ready to start; on any failure the
     *          player is released and the temp file deleted.
     */
    fun prepare(bytes: ByteArray, extension: String, cacheDir: java.io.File): Boolean {
        var tmp: java.io.File? = null
        val mp = android.media.MediaPlayer()
        return runCatching {
            tmp = java.io.File.createTempFile("verzeta-audio-", ".$extension", cacheDir)
                .also { it.writeBytes(bytes) }
            mp.setDataSource(tmp!!.absolutePath)
            mp.prepare()
            synchronized(this) {
                prepared = mp
                tempFile = tmp
            }
            true
        }.getOrElse {
            mp.release()
            tmp?.delete()
            false
        }
    }

    /** Start the prepared player on the main thread. */
    fun start(fileName: String) {
        val mp = synchronized(this) { prepared.also { prepared = null } } ?: return
        mp.setOnCompletionListener { stop() }
        mp.setOnErrorListener { _, _, _ -> stop(); true }
        player = mp
        playingFile = fileName
        mp.start()
    }

    /** Stop and release the current player, if any, and delete its temp file. */
    fun stop() {
        val mp = player
        player = null
        playingFile = null
        if (mp != null) {
            runCatching { mp.stop() }
            mp.release()
        }
        synchronized(this) {
            prepared?.release()
            prepared = null
            tempFile?.delete()
            tempFile = null
        }
    }
}

@Composable
private fun AudioRow(
    clip: GeneratedFileUi,
    playing: Boolean,
    onPlay: () -> Unit,
    onStop: () -> Unit,
) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(8.dp))
            .background(MaterialTheme.colorScheme.surfaceContainerLow)
            .border(1.dp, MaterialTheme.colorScheme.outlineVariant, RoundedCornerShape(8.dp))
            .padding(horizontal = 12.dp, vertical = 10.dp),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        Icon(
            Icons.Filled.Audiotrack,
            contentDescription = null,
            tint = MaterialTheme.colorScheme.onSurfaceVariant,
        )
        Spacer(Modifier.size(10.dp))
        Column(modifier = Modifier.weight(1f)) {
            Text(
                clip.fileName,
                style = MaterialTheme.typography.bodyMedium.copy(fontFamily = FontFamily.Monospace),
                maxLines = 1,
                overflow = TextOverflow.Ellipsis,
            )
            Text(
                "${clip.totalBytes / 1024} KB",
                style = MaterialTheme.typography.labelSmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
            )
        }
        if (playing) {
            IconButton(onClick = onStop) {
                Icon(Icons.Filled.Stop, contentDescription = "Stop")
            }
        } else {
            IconButton(onClick = onPlay) {
                Icon(Icons.Filled.PlayArrow, contentDescription = "Play")
            }
        }
    }
}
